### ISSUE TITLE
Running the contributed command: '_svg.minifySvg' failed.

### ISSUE THREAD

**Issue by xperiments** [lishu/vscode-svg2#2]
Actually I am getting this error when running the minify command.

I have noticed when I activate your plugin code coloring gets strange:

![image](https://user-images.githubusercontent.com/417709/65138205-e2234080-da0a-11e9-94d3-6e973d26e632.png)

With extension disabled
![image](https://user-images.githubusercontent.com/417709/65138278-02eb9600-da0b-11e9-8176-a1256663a2b9.png)

IDK if helps... Thanks!!!!

**Comment by vbarinov** [comment]
Complete error log. 

- MacOS 10.14.6
- VSCode Version: 1.38.1

```sh
[exthost] [error] Error: ENOENT: no such file or directory, open '//../../.svgo.yml'
	at Object.openSync (fs.js:436:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
	at Object.readFileSync (fs.js:341:35)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:580:40)
	at module.exports.e.exports (/Users/vvbarinov/.vscode/extensions/jock.svg-1.0.1/client/out/extension.js:87:142338)
	at new c (/Users/vvbarinov/.vscode/extensions/jock.svg-1.0.1/client/out/extension.js:10:103)
	at u (/Users/vvbarinov/.vscode/extensions/jock.svg-1.0.1/client/out/extension.js:87:140468)
	at module.exports.t.svgMinify (/Users/vvbarinov/.vscode/extensions/jock.svg-1.0.1/client/out/extension.js:87:140851)
	at t.createApiFactoryAndRegisterActors._.registerTextEditorCommand.me.registerCommand.r.edit.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:866)
	at f.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:484:54)
	at t.createApiFactoryAndRegisterActors._.registerTextEditorCommand.me.registerCommand.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:840)
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518:163)
	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518:538)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623:396)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623:88)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:783)
	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:605)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:618:791)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:579)
	at i.constructor.e.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:484)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:579)
	at x._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:191:17)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188:116)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at f.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:184:17)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:183:372)
	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:192:491)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) _svg.minifySvg
```

**Comment by lishu** [comment]
Thank for report this issues.
Path data highlight can be disable in **Next release** if you don't like.
The Package use webpack causing this problem. Still looking for a solution, please wait some time.
